#pragma once

#include "SDL3/SDL.h"
#include "Bitmap.h"
#include "Player.h"
#include "Monster.h"
#include "Input.h"
#include "Debug.h"
#include "GameObject.h"
#include "BitmapComponent.h"
#include "ECS.h"
#include "RendererSystem.h"
#include "MovementSystem.h"
#include "StackArenaAllocator.h"
#include "Sol/sol.hpp"
#include "ScriptComponent.h"
#include "imgui.h"
#include "ImGui/backends/imgui_impl_sdl3.h"
#include "ImGui/backends/imgui_impl_sdlrenderer3.h"
#include "EditorGui.h"
#include "AssetWindow.h"
#include "SaveLoadSystem.h"
#include "ProfilerSystem.h"
#include "irrKlang.h"
#include <iostream>
#include <random>
#include <fstream>
#include "json.hpp"
#include <imgui_internal.h>
